#message:2F:(Menus_GotFireball) {
	[DelayOff]
	[Style popup]
	[Color 0x2F]You got the[BR]
	[Color 0x28]Fireball![Color 0x2F]![BR]
	[DelayOn]
	[Wait][End]
}

#message:2F:(ItemName_Fireball) {
	Fireball[End]
}

#message:2F:(ItemFullDesc_Fireball) {
	Allows Mario to shoot fireballs[BR]
	from his hands by pressing [C-DOWN] [End]
}

#message:2F:(ItemShortDesc_Fireball) {
	Allows Mario to shoot fireballs[BR]
	from his hands by pressing [C-DOWN] [End]
}

#message:2F:(Menus_GotPWing) {
	[DelayOff]
	[Style popup]
	[Color 0x2F]You got the[BR]
	[Color 0x28]P-Wing![Color 0x2F]![BR]
	[DelayOn]
	[Wait][End]
}

#message:2F:(ItemName_PWing) {
	P-Wing[End]
}

#message:2F:(ItemFullDesc_PWing) {
	Allows Mario to airdash[BR]
	by pressing [Z] mid-air [End]
}

#message:2F:(ItemShortDesc_PWing) {
	Allows Mario to airdash[BR]
	by pressing [Z] mid-air [End]
}

#message:2F:(NPC_KooperThanks) {
	[Style right]
	I found this on the way while[BR]
	looking for my shell, please take it![Wait][End]
}

#message:2F:(NPC_BombetteHelps) {
	[Style right]
	What's that...?[BR]
	[Pause 10]Cracked walls?[BR]
	Explosions?[BR]
	[Wait][Next]
	Look, I'm not leaving without [BR]
	these guys...
	[Pause 10]Aren't you the [BR]
	Super Mario? With a hammer too...[BR]
	[Pause 5]What do you mean, too weak?[BR]
	[Wait][Next]
	Have confidence! There's no way [BR]
	some cracked wall is too much [BR]
	for a legend like you![BR]
	Give that thing a wack![BR]
	[Wait][End]
}

#message:2F:(NPC_BombetteConfidence) {
	[Style right]
	Have confidence! There's no way [BR]
	some cracked wall is too much [BR]
	for a legend like you![BR]
	Give that thing a wack![BR]
	[Wait][End]
}

#message:2F:(NPC_BombetteGoodLuck) {
	[Style right]
	Good luck Mario! Show these [BR]
	nasty koopas who is the boss! [BR]
	[Wait][End]
}

#message:2F:(NPC_ParakarryWatchYourStep) {
	[Style right]
	Hey!!!![BR]
	[Pause 5]Watch where you're going![BR]
	[Wait][Next]
	I have no time for this, move![Wait][End]
}
