#message:2F:(Menus_GotFireball) {
	[DelayOff]
	[Style popup]
	[Color 0x2F]You got the[BR]
	[Color 0x28]Fireball![Color 0x2F]![BR]
	[DelayOn]
	[Wait][End]
}

#message:2F:(ItemName_Fireball) {
	Fireball[End]
}

#message:2F:(ItemFullDesc_Fireball) {
	Allows Mario to shoot fireballs[BR]
	from his hands by pressing [C-DOWN] [End]
}

#message:2F:(ItemShortDesc_Fireball) {
	Allows Mario to shoot fireballs[BR]
	from his hands by pressing [C-DOWN] [End]
}

#message:2F:(Menus_GotPWing) {
	[DelayOff]
	[Style popup]
	[Color 0x2F]You got the[BR]
	[Color 0x28]P-Wing![Color 0x2F]![BR]
	[DelayOn]
	[Wait][End]
}

#message:2F:(ItemName_PWing) {
	P-Wing[End]
}

#message:2F:(ItemFullDesc_PWing) {
	Allows Mario to airdash[BR]
	by pressing [Z] mid-air [End]
}

#message:2F:(ItemShortDesc_PWing) {
	Allows Mario to airdash[BR]
	by pressing [Z] mid-air [End]
}

#message:2F:(Menus_GotSlowGhost) {
	[DelayOff]
	[Style popup]
	[Color 0x2F]You got the[BR]
	[Color 0x28]Slow Ghost![Color 0x2F]! Badge[BR]
	[DelayOn]
	[Wait][End]
}

#message:2F:(ItemName_SlowGhost) {
	Slow Ghost[End]
}

#message:2F:(ItemFullDesc_SlowGhost) {
	Makes Mario invisible, at the cost[BR]
	of moving very slowly.[End]
}

#message:2F:(ItemShortDesc_SlowGhost) {
	Makes Mario invisible, at the cost[BR]
	of moving very slowly.[End]
}

#message:2F:(NPC_KooperThanks) {
	[Style right]
	I found this on the way while[BR]
	looking for my shell, please take it![Wait][End]
}

#message:2F:(NPC_BombetteHelps) {
	[Style right]
	What's that...?[BR]
	[Pause 10]Cracked walls?[BR]
	Explosions?[BR]
	[Wait][Next]
	Look, I'm not leaving without [BR]
	these guys...
	[Pause 10]Aren't you the [BR]
	Super Mario? With a hammer too...[BR]
	[Pause 5]What do you mean, too weak?[BR]
	[Wait][Next]
	Have confidence! There's no way [BR]
	some cracked wall is too much [BR]
	for a legend like you![BR]
	Give that thing a wack![BR]
	[Wait][End]
}

#message:2F:(NPC_BombetteConfidence) {
	[Style right]
	Have confidence! There's no way [BR]
	some cracked wall is too much [BR]
	for a legend like you![BR]
	Give that thing a wack![BR]
	[Wait][End]
}

#message:2F:(NPC_BombetteGoodLuck) {
	[Style right]
	Good luck Mario! Show these [BR]
	nasty koopas who is the boss! [BR]
	[Wait][End]
}

#message:2F:(NPC_ParakarryWatchYourStep) {
	[Style right]
	Hey!!!![BR]
	[Pause 5]Watch where you're going![BR]
	[Wait][Next]
	I have no time for this, move![Wait][End]
}

#message:2F:(NPC_BowGoodDeal) {
	[Style right]
	What do you think, Mario?[BR]
	[Pause 10]A good deal, isn't it?[BR]
	[Wait][Next]
	Just wack a few baddies like[BR]
	you always do, and you're off[BR]
	with this star spirit![BR]
	[Wait][End]
}

#message:2F:(NPC_Bow_TakeThisBadge) {
	[Style right]
	Here, take this badge.[BR]
	[Wait][Next]
	You can use it to hide and get [BR]
	past Tubba Blubba's guards.[BR][Wait][Next]
	Oh, and I'll tell the guards to [BR]
	let you through Gusty Gulch. [Wait] [End]
}

#message:2F:(NPC_StanleyHide) {
	[Style right]
	Uh oh...[BR]
	[Pause 10]Tubba Blubba's coming![BR]
	[Pause 10]Everyone, hide!![BR]
	[Wait][Next]
	Mario![BR]
	[Pause 10]Use your Slow Ghost badge![Wait][End]
}

#message:0E:(NPC_StanleyCool) {
	[Style right]
	Everything's cool, Mario![BR]
	[Pause 10]He can't see you! Remember,[BR]
	you can toggle this ability[BR]
	anytime in the badges menu![Wait][End]
}
